{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red42\green44\blue51;\red42\green40\blue35;\red50\green94\blue238;
\red39\green38\blue34;\red219\green63\blue57;\red66\green147\blue62;}
{\*\expandedcolortbl;;\cssrgb\c21961\c22745\c25882;\cssrgb\c21569\c20784\c18431\c3922;\cssrgb\c25098\c47059\c94902;
\cssrgb\c20392\c19608\c17647;\cssrgb\c89412\c33725\c28627;\cssrgb\c31373\c63137\c30980;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24\fsmilli12250 \cf2 \cb3 \expnd0\expndtw0\kerning0
[\cf4 build\cf2 ]\cf5 \
\pard\pardeftab720\partightenfactor0
\cf6   command\cf2  = \cf7 "npm install --legacy-peer-deps && npm run build"\cf5 \
\cf6   publish\cf2  = \cf7 ".next"\cf5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 [\cf4 build\cf2 .\cf4 environment\cf2 ]\cf5 \
\pard\pardeftab720\partightenfactor0
\cf6   NODE_VERSION\cf2  = \cf7 "16.14.0"\cf5 \
\cf6   NPM_FLAGS\cf2  = \cf7 "--legacy-peer-deps"}